[project]
name = "career-agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "chromadb",
    "pydantic",
    "python-dotenv",
    "tiktoken",
    "langchain-text-splitters",
    "gradio>=4.44.1",
    "openai-agents>=0.13.6",
    "sendgrid>=6.12.5",
    "audioop-lts>=0.2.2 ; python_full_version >= '3.13'",
    "setuptools>=82.0.1",
]
